---
# Copy nginx block (vhost) config files
- name: Copy nginx block (vhost) config file to available sites
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_conf_dir }}/sites-available/{{ collabora_fqdn }}.conf"
  with_items:
    - nginx.conf
  notify: "reload nginx"
  become: yes

- name: Enable nginx block config
  file:
    src: "{{ nginx_conf_dir }}/sites-available/{{ collabora_fqdn }}.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/{{ collabora_fqdn }}.conf"
    state: link
  notify: "reload nginx"
  become: yes
